package io.mymetavese.metaapi.requests.routes;

public enum Routes {
    LINK_PLAYER,

    GET_WALLET,

    GET_ETH_ADDRESS,

    CREATE_LINKING_LINK,

    GET_LINKING_LINK,

    GET_TOKEN_METADATA,
    UPDATE_TOKEN_DETAILS,
    UPDATE_TOKEN_PROPERTY,
    DELETE_TOKEN_PROPERTY,

    UPDATE_TOKEN_INDEX_DETAILS,
    UPDATE_TOKEN_INDEX_PROPERTY,
    DELETE_TOKEN_INDEX_PROPERTY,

    GET_ACTIVE_META_CITIZEN,

    GIVE_WHITELISTED_TOKEN,

    // Play2Earn Routes
    GET_P2E_POINTS,
    ADD_P2E_POINTS,

    // MetaDrops Routes
    GET_ALL_DROPS,
    GET_DROP,
    CONSUME_DROP

}
