version: 2.1
# asd
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.272
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_artifacts:
          path: ./target/*.jar
          destination: target

      - persist_to_workspace:
          root: ./
          paths:
            - target/

  test:
    docker:
      - image: cimg/openjdk:8.0.272
    steps:
      - checkout

      - attach_workspace:
          at: ./target

      - run:
          name: Test
          command: mvn test

      - store_test_results:
          path: test-results

  deploy:
      docker:
        - image: cimg/openjdk:8.0.272

      steps:
        - checkout

        - attach_workspace:
            at: ./target

        - run:
            name: Init GPG
            command: |
              gpg --batch --import <(echo -e $GPG_KEY)

        - run:
            name: Create settings.xml
            command: |
              cd ~/project && gpg --batch --decrypt settings.xml.gpg >> ~/.m2/settings.xml


        - run:
            name: Deploy
            command: mvn deploy


workflows:
  build-test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/

      - test:
          requires:
            - build

  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - test:
          requires:
            - build

      - deploy:
          context: MavenDeployment
          requires:
            - test