name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test JavaSDK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Test with Maven
      run: mvn -B test

  build-and-archive:
  
    name: Build JavaSDK and Archive Artifact
    runs-on: ubuntu-latest
    needs: [ test ]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build JavaSDK
      run: mvn -B -DskipTests=true package
      
    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: JavaSDK-Artifact
        path: ./target/**.jar
